version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./frames:/app/frames
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - TZ=UTC
